root: true
extends:
  - airbnb-base
  - airbnb-typescript/base
parserOptions:
  project:
    - ./tsconfig.json
    - ./tsconfig.unit.json
plugins:
  - import
  - chai-friendly
rules:
  '@typescript-eslint/indent': off
  no-underscore-dangle: off
  max-classes-per-file: off # factory method in abstract base class requires multiple sub-classes in the same file
  '@typescript-eslint/no-use-before-define': off # factory method in abstract base class requires multiple sub-classes in the same file
  '@typescript-eslint/prefer-literal-enum-member':
    - error
    - allowBitwiseExpressions: true
  import/extensions:
    - error
    - never
    - mjs: always # ESM import requires the full name
  '@typescript-eslint/no-unused-expressions': off
  chai-friendly/no-unused-expressions: error
  no-bitwise:
    - error
    - allow:
        - <<
  eol-last:
    - error
    - always
settings:
  import/resolver:
    typescript:
      project:
        - tsconfig.json
        - tsconfig.unit.json
overrides:
  - files:
    - test/**
    env:
      mocha: true
