name: Build & Test
on: workflow_call
env:
  EM_VERSION: 3.1.44
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Emcripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{ env.EM_VERSION }}
      - name: Install npm packages
        run: npm ci
      - name: Build the library
        run: npm run build
      - name: Test
        run: npm run test
