name: Doc Site Build
on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      version:
        required: true
        type: string
jobs:
  build:
    name: Build Doc
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install npm packages
        run: npm ci
      - name: Build the document
        run: npm run doc
      - name: Checkout the site
        uses: actions/checkout@v4
        with:
          path: site
          ref: gh-pages
      - name: Find variables
        id: vars
        # if no version, should be on master branch push, use "dev", otherwise major.minor
        run: |
          [ -z "${{ inputs.version }}" ] && (echo version=dev >> $GITHUB_OUTPUT) || (echo version=v${{ inputs.version }} | cut -d "." -f 1,2 >> $GITHUB_OUTPUT)
          echo git_msg=\"$(git log -1 --pretty=format:'%s')\" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: build site
        run: |
          rm -rf site/${{ steps.vars.outputs.version }}
          mv _site site/${{ steps.vars.outputs.version }}
      - name: Commit to site branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: site
          branch: gh-pages
          commit_message: Doc of version ${{ steps.vars.outputs.version }} generated from ${{ steps.vars.outputs.sha_short }} ${{ steps.vars.outputs.git_msg }}
          skip_dirty_check: false
          skip_fetch: true
          skip_checkout: true
