name: PR Build
on: pull_request
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Show variables
        run: |
          echo "github.event.pull_request.merge_commit_sha = ${{ github.event.pull_request.merge_commit_sha }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.sha = ${{ github.sha }}"
          find .git/refs
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"
          submodules: true
  Build:
        uses: jameslan/libxml2-wasm/.github/workflows/continuous-integration.yml@feature/ci
        needs: Checkout
