name: PR Build
on: pull_request
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"
          submodules: true
  Build:
        uses: jameslan/libxml2-wasm/.github/workflows/continuous-integration.yml@feature/ci
        needs: Checkout
